import os
import collections
from Bio import SeqIO

outputPath=config["outputPath"]


##### Target rules #####

rule all:
    input:
        expand(outputPath + "/binned/barcode_{barcode}/references/{analysis_stem}.fasta", barcode=config["barcode"], analysis_stem = config["analysis_stem"]),
        expand(outputPath+"/binned/barcode_{barcode}/orf_binned/barcode_{barcode}_{analysis_stem}.fastq", analysis_stem=config["analysis_stem"],barcode=config["barcode"]),
        expand(outputPath+"/consensus_sequences/{barcode}.fasta",barcode=config["barcode"])

##### Modules #####
include: "rules/bin.smk"
include: "rules/map_polish.smk"
