run_name: noro_GOSH_2k
path_to_fastq: /Volumes/aine_store/20190503_2312_gosh_3runs_030519/GOSH_fastq
path_to_fast5: /Volumes/aine_store/20190503_2312_gosh_3runs_030519/fast5
reference_file: primer-schemes/noro2kb/V2/noro2kb.reference.fasta
primer_scheme_dir: primer-schemes
primer_scheme_version: noro2kb/V2
min_length: 1000
max_length: 3000
barcodes:
    # barcodeX: barcodeX
    # barcode01: barcode01
    # barcode02: barcode02
    # barcode03: barcode03
    # barcode04: barcode04
    # barcode05: barcode05
    # barcode06: barcode06
    barcode07: barcode07
    # barcode08: barcode08
    # barcode09: barcode09
    # barcode10: barcode10
    # barcode11: barcode11
    # barcode12: barcode12
    # barcode13: barcode13
    # barcode14: barcode14
    # barcode15: barcode15
    # barcode16: barcode16
    # barcode17: barcode17
    # barcode18: barcode18
    # barcode19: barcode19
    # barcode20: barcode20
    # barcode21: barcode21
    # barcode22: barcode22
    # barcode23: barcode23
    # barcode24: barcode24
amplicons:
  Amp1: Amp1
  Amp2: Amp2
  Amp3: Amp3
  Amp4: Amp4
  Amp5: Amp5
samples:
    # GOSH_2kb01: barcode01
    # GOSH_2kb02: barcode02
    # GOSH_2kb03: barcode03
    # GOSH_2kb04: barcode04
    # GOSH_2kb05: barcode05
    # GOSH_2kb06: barcode06
    GII6_2kb07: barcode07
    # GII6FS_2kb08: barcode08
    # GOSH_3kb09: barcode09
    # GOSH_3kb10: barcode10
    # GOSH_3kb11: barcode11
    # GOSH_3kb12: barcode12
    # GOSH_3kb13: barcode13
    # GOSH_3kb14: barcode14
    # GII6_3kb15: barcode15
    # GII6FS_3kb16: barcode16
    # GOSH_7kb17: barcode17
    # GOSH_7kb18: barcode18
    # GOSH_7kb19: barcode19
    # GOSH_7kb20: barcode20
    # GOSH_7kb21: barcode21
    # GOSH_7kb22: barcode22
    # GII6_7kb23: barcode23
    # GII6FS_7kb24: barcode24



