run_name: noro_GOSH_2k
path_to_fastq: /Volumes/aine_store/
path_to_fast5: /Volumes/aine_store/
reference_file: references/genes.fasta
primer_scheme_dir: primer-schemes
primer_scheme_version: PV/V1
min_length: 200
max_length: 2500
barcodes:
    BC01: BC01
    BC02: BC02
    BC03: BC03
    BC04: BC04
    BC05: BC05
    BC06: BC06
    BC07: BC07
    BC08: BC08
    BC09: BC09
    BC10: BC10
    BC11: BC11
    BC12: BC12
ORFS:
  ORF1: ORF1
  ORF2: ORF2



