file_stem: sample_reads #the stem of the fastq file you wish to run through the pipeline

#Where is the data and where should it be put

basecalledPath: path/to/data #where rampart will find the data
outputPath: path/to/data #where rampart will put the data

#For mapping
referencePanelPath: references.fasta
referenceConfigPath: coordinate_reference.fasta
bedPath: scheme.bed # this is optional

#The following are all porechop options

require_two_barcodes: "--require_two_barcodes"
discard_middle: "--discard_middle"
no_split: "--no_split"
discard_unassigned: "--discard_unassigned"
demuxOption: "--native_barcodes"

# binning options

barcode : BCXX
min_length: 400
max_length: 2400

