
##### Config file #####

configfile: "pipelines/rampart_demux_map/config.yaml"

##### Pipeline variables #####

#demuxedPath = str(config["demuxedPath"]).rstrip('/')
#basecalledPath = str(config["basecalledPath"]).rstrip('/')
#referencePanelPath = str(config["referencePanelPath"])
#referenceConfigPath = str(config["referenceConfigPath"])
#print(referencePanelPath)
#bedPath = str(config["bedPath"])

##### Target rules #####
rule all:
    input:
        expand(config["demuxedPath"]+ "/annotated_reads/{file_stem}.fastq", file_stem=config["file_stem"])

##### Modules #####
include: "rules/demultiplex.smk"
include: "rules/map.smk"

