run_name: Noro2kb
outputPath: pipeline_output
readPath: validator_output/{reference}/simulated_sample/
# referencePanelPath : path/to/references.fasta
# primer_scheme_dir: primer-schemes
# primer_scheme_version: noro2kb/V2
min_length: 800
max_length: 2600
custom_bin: 
orf: 
  ORF_1: [1,5370] 
  ORF_2_3: [5354,7600]
barcode: NB24
amplicons:
  -  Amp1
  -  Amp2
  -  Amp3
  -  Amp4
  -  Amp5

