import os
import collections
from Bio import SeqIO

configfile: "pipelines/bin_filter/config.yaml"


##### Target rules #####

rule all:
    input:
        expand(config["output_dir"] + "/binned/barcode_{barcode}/config.yaml",barcode=config["barcode"]),
        expand(config["output_dir"] + "/binned/barcode_{barcode}/barcode_{barcode}.fastq",barcode=config["barcode"])



##### Modules #####
include: "rules/bin.smk"
#include: "rules/bin_amplicons.smk"
#include: "rules/generate_consensus.smk"
#include: "rules/map_polish.smk"

#onstart:
#    print("Setting up binlorry")
#    shell("cd ../binlorry && pip install binlorry")
##    shell("export PATH=$PATH:`pwd`/binlorry")
#    shell("cd ../artic-noro ")
