### tested with ansible 2.3.1 and ubuntu 16.04 cloud image on CLIMB

---

- hosts: localhost
  gather_facts: false

  tasks:
  - name: load users and  passwords
    include_vars: users.yml
    tags: users

  - name: create users
    user: name="{{ item.key }}" password="{{ item.value }}" shell="/bin/bash" update_password=on_create
    with_dict: "{{ user_passwords }}"
    register: user_results
    tags: users

  - name: update apt cache
    apt: update_cache=yes

  - name: install packages
    apt: name={{ item }} state=present
    with_items:
      - bzip2
      - git
      - default-jre
      - gnuplot-x11
      - bioperl
      - libssl-dev
      - texlive
      - texlive-latex-extra
      - cmake
      - artemis
      - hdf5-tools
      - libdatetime-perl
      - libxml-simple-perl
      - libdigest-md5-perl
      - libfreetype6-dev
      - pkg-config

  - name: install conda and conda packages
    include_tasks: conda.yml
    become_user: "{{ item.item.key }}"
    with_items:
      - "{{ user_results.results }}"

## Software from ONT

  - name: add nanopore key
    apt_key: url=https://mirror.oxfordnanoportal.com/apt/ont-repo.pub state=present

  - name: add nanopore repo
    apt_repository:
      repo: deb http://mirror.oxfordnanoportal.com/apt xenial-stable non-free
      state: present
      filename: nanoporetech

  - name: install python3-ont-fast5-api
    apt: name=python3-ont-fast5-api state=present allow_unauthenticated=yes

  - name: minknow
    apt: name=minknow-nc state=present allow_unauthenticated=yes

  - name: install ont-albacore wheel
    become_user: "{{ item.item.key }}"
    pip: name=https://mirror.oxfordnanoportal.com/software/analysis/ont_albacore-2.3.0-cp36-cp36m-manylinux1_x86_64.whl executable=/home/{{ item.item.key }}/miniconda3/bin/pip
    with_items:
       - "{{ user_results.results }}"

  - name: install guppy
    apt: name=ont-guppy state=present

  - name: artic primer schemes github
    git: repo=https://github.com/artic-network/primer-schemes.git dest=/artic force=yes

  - name: artic pipeline
    pip: name='git+https://github.com/artic-network/fieldbioinformatics.git' executable=/home/{{ item.item.key }}/miniconda3/bin/pip
    with_items:
       - "{{ user_results.results }}"

